### ISSUE TITLE
Time Zone Compensation

### ISSUE THREAD

**Issue by weltermarcel** [corbosman/node-red-contrib-timerswitch#1]
Hi, is there a way to set a different time zone?

**Comment by jgtaylor** [comment]
Does this module only support UTC?

**Comment by corbosman** [comment]
It uses whatever timezone the operating system is in. So if the raspberry pi (or whatever) says it 10am, and you set a timer for 11am, it will come on an hour later.

**Comment by jgtaylor** [comment]
That makes sense. I realized I need to keep things in UTC since nature doesn't change its clocks.

Thanks!
