### ISSUE TITLE
FR: Full-format output selectors

### ISSUE THREAD

**Issue by daxliniere** [corbosman/node-red-contrib-timerswitch#17]
Hello!
I just discovered your timer module which looks like it'll do the trick nicely, but I've found that the output options don't allow me to set a JSON payload nor a string topic. This is what I need:

![image](https://github.com/corbosman/node-red-contrib-timerswitch/assets/8109020/95b2012b-d274-4c35-8fa2-44b5608382f4)

Another approach would be to have separate outputs for high and low, then I could route them to the separate on and off trigger nodes. I suppose there could be an option inside your module and when 'dual output' is disabled, high and low would both come out of the first output.

Is this something you might be able to implement?

All the best,
Dax.

**Comment by corbosman** [comment]
You can probably just connect a "switch" node to my timerswitch and modify the output to your liking based on input coming from my timerswitch. I'm not really adding new features. It's been running flawlessly on my terrarium for over 5 years and that's really all I wrote it for.

**Comment by daxliniere** [comment]
Well, thanks for sharing anyway.

**Comment by daxliniere** [comment]
I worked out a solution if anyone else needs it. Drop this into a Function node and in the Setup tab, change to 2 outputs.

```
if (msg.payload == 1) {
    msg.payload = 1;
    node.status({ fill: "green", shape: "circle" });
    return [{payload: msg},null];
} else if (msg.payload == 0){ 
    msg.payload = 1;
    node.status({ fill: "red", shape: "circle" });
    return [null,{payload: msg}];
}
```

**Comment by corbosman** [comment]
That's why I mentioned the switch node, I think you can do exactly that without using the Function node right? You can add multiple output based on inputs (0 or 1)
