### ISSUE TITLE
Allow boolean output

### ISSUE THREAD

**Issue by renne** [corbosman/node-red-contrib-timerswitch#6]
Timerswitch is limited to string output. Some nodes (e.g. switch) need boolean input.
Please allow boolean `true/false` for `on/off` payload.

**Comment by corbosman** [comment]
You can just add a simple change node right?  That's really the philosophy behind node-red. Dont have a single node try and please everything, but use multiple nodes to generate a flow of options.

**Comment by jgtaylor** [comment]
simply outputing "true" or "false" should be truthy or falsey enough for
the double equals (==)
